baseURL = "https://hugo-theme-shell.netlify.app/"
languageCode = "en-us"
title = "Terminal@Yiran"
theme = "hugo-theme-shell"

[Params]
    [Params.Terminal]
    schema = "gruvbox_dark"
    userName = "root"
    pcName = "terminal5"
    workDir = "doc"
    profile = "readme.nfo"    
    # Note: speed at which text is displayed on the terminal
    # Note: if set to 0, typing animation will be disabled
    # Note:
    # Note: if you want to enable Mathjax, you need to set it to 0
    # Note: and set "math: true" at front matter in your Markdown file
    ps1Delay = 10 # prompt speed : [userName]@[pcName]:~/$ , [userName]@[pcName]:~/[workDir]$
    stdoutDelay = 25 # stdout speed : [description] , files in Params.Tree
    commandDelay = 50 # command speed : cd [workDir] , cat [profile] , tree ./[folderName]/

    # terminalDelay = 20 : deprecated

    # Note: speed at which text is displayed on the activity pages
    # Note: if set to 0, typing animation will be disabled
    # Note: 
    # Note: if you want to enable Mathjax, you need to set it to 0
    # Note: and set "math: true" at front matter in your Markdown file
    titleDelay = 20 # title speed : "title" in front matter
    contentDelay = 20 # content speed : content in .md file

    description = """
    Welcome to my personal website
    where the returns are always high and the risk is always low 
    # just like my backtest results with DNN...

    My name is Yiran Liu and I specialize in quantitative trading. 
    Let's make some data-driven decisions together  

    """

    description2 = """
    description2 lalala 
    """
    
    [Params.Tree]
    use = true    
    folderName = "var/log"
    files = [
        ["log_exp_hk_ms_21.log", "/"],
		["log_exp_hk_jpm_19.log", "/"],
		["log_exp_ln_avt_17.log", "/"],
		["log_exp_ln_cmc_12.log", "/"],
		["log_exp_ln_oak_11.log", "/"],
		["log_edu_ln_ic_16.log", "/"],
		["log_edu_ln_kcl_11.log", "/"],
		["log_edu_cn_xj~sh_~.log", "/"]
    ]
